spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: 'true'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: 'true'
  security:
    filter:
      order: '10'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    username: root
    url: jdbc:mariadb://localhost:3306/ohmyclass
springdoc:
  api-docs:
    enabled: true
    path: "/api-docs"
  swagger-ui:
    enabled: true
server:
  error:
    include-stacktrace: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
        hibernate: DEBUG
        jdbc: DEBUG
        jpa: DEBUG
        transaction: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
constants:
  jwt:
    tokenprefix: "Bearer "
    secret: "very secure secret" # TODO Improve
    expiration:
      access_token: 600000 # 10 minutes
      refresh_token: 3600000 # 1 hour
    uriwhitelist:
      - "/api/v1/auth/login"
      - "/api/v1/auth/register"
      - "/api/v1/auth/forgotten"
      - "/api/v1/auth/refresh"
      - "/api-docs"
      - "/swagger-resources/"
      - "/swagger-ui"
    claims:
      roles: "rls"
  api:
    urls:
      base_url: "/api/v1"
      login_url: "auth/login"
      register_url: "auth/register"
      refresh_url: "auth/refresh-token"
      forgotten_pw_url: "auth/password-forgotten"
      user_get_url: "/user/get{id}"
      user_update_url: "/user/update"
      user_delete_url: "/user/delete"